packages:
  - "packages/*"
publicHoistPattern:
  - "@types/*"
  - "typescript"
  - "vite"
  - "turbo"
  - "vitest"
  - "@vitest/*"
autoInstallPeers: true
strictPeerDependencies: false
preferFrozenLockfile: true
